version: 0.2

env:
  parameter-store:
    SERVERLESS_ACCESS_KEY: serverless-access-key
    
phases:
  install:
    run-as: root
    on-failure: ABORT 
    commands:
      - npm install
      - npm install -g serverless
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  
  build:
    run-as: root
    on-failure: ABORT
    commands:
      - sls deploy