version: 0.2

env:
  parameter-store:
    SERVERLESS_ACCESS_KEY: serverless-access-key
    
phases:
  install:
    run-as: root
    on-failure: ABORT 
    commands:
      - npm install
      - npm install -g serverless
    
  
  build:
    run-as: root
    on-failure: ABORT
    commands:
      - sls deploy