version: 0.2

env:
    parameter-store:
        SERVERLESS_CICD_S3_BUCKET: serverless-cicd-s3-bucket

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g newman
      - yum install -y jq

  pre_build:
    commands:
      - aws s3 cp "s3://myhealth-cicd-pipeline/postman-env-files/myHealth.postman_environment.json" ./postman/
      - aws s3 cp "s3://myhealth-cicd-pipeline/postman-env-files/myHealth.postman_collection.json" ./postman/
      - cd ./postman

  build:
    commands:
      - echo Build started on `date` from dir `pwd`
      - newman run myHealth.postman_collection.json --environment myHealth.postman_environment.json -r junit

reports:
  JUnitReports: # CodeBuild will create a report group called "SurefireReports".
    files: #Store all of the files
      - '**/*'
    base-directory: 'postman/newman' # Location of the reports